### ISSUE TITLE
Consider scripts section similar to npm package.json

### ISSUE THREAD

**Issue by proofit404** [kennethreitz/pipenv#153]
Hi, thanks for yet another awesome tool!

I wander if there is any plans to add commands abbreviations for example in scripts section.

So instead of typing each time `pipenv run python -m unittest discover` it will be enough to run `pipenv test`  (or maybe `pipenv apply test`) if we have this in the Pipfile:

```toml
[[scripts]]
test = "python -m unittest discover"
```
