### ISSUE TITLE
Trouble running pipenv in CI

### ISSUE THREAD

**Issue by lburdzy** [kennethreitz/pipenv#290]
I've been trying to get pipenv to work with gitlab CI, but i'm getting errors. Here are last lines of output:
```
To activate this project's virtualenv, run the following:
 $ pipenv shell
$ pipenv run --no-interactive python manage.py migrate
ERROR: Job failed: exit code 1
```
And here is my .gitlab.ci.yaml
```yaml
# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python
image: python:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
services:
  - postgres:latest

variables:
  POSTGRES_DB: db
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - ~/.cache/pip/

# This is a basic example for a gem or script which doesn't use
# services such as redis or postgres
before_script:
  - python -V                                   # Print out python version for debugging
  # Uncomment next line if your Django app needs a JS runtime:
  # - apt-get update -q && apt-get install nodejs -yqq
  - pip install pipenv
  - pipenv install --dev

test:
  variables:
    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"
  script:
  - pipenv run python manage.py migrate
  - pipenv run python manage.py test
  - pipenv run coverage run -m pytest
  - pipenv run coverage run report
```
Any idea why it fails? I did also try to run `pipenv shell`, but that failed too.
