### ISSUE TITLE
VCS install with extras doesn't work

### ISSUE THREAD

**Issue by RazerM** [kennethreitz/pipenv#296]
I tried to install an extra with a VCS install like so:

```
pipenv install git+https://github.com/RazerM/represent.git@1.5.1#egg=represent[test]
```

The extra gets installed, but a broken Pipfile is created:

```toml
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true

[packages."represent[test]"]
git = "https://github.com/RazerM/represent.git"
ref = "1.5.1"
```

---

I also tried to alter the Pipfile manually like this:
```toml
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true

[packages.represent]
git = "https://github.com/RazerM/represent.git"
ref = "1.5.1"
extras = [ "test", ]
```

but that does not include the extras in the lockfile:

```json
{
    "_meta": {
        "hash": {
            "sha256": "39fb25d347273465fc9b0f560bad46abf343f137dc9f48fef7bbd01c39fe328f"
        },
        "requires": {},
        "sources": [
            {
                "url": "https://pypi.python.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "represent": {
            "extras": [
                "test"
            ],
            "git": "https://github.com/RazerM/represent.git",
            "ref": "1.5.1"
        }
    },
    "develop": {}
}
```
