### ISSUE TITLE
Pipfile syntax invalid when installing editable requirements with extras_require flag.

### ISSUE THREAD

**Issue by ticosax** [kennethreitz/pipenv#430]
For given command:
```bash
pipenv install  "git+https://github.com/requests/requests.git@master#egg=requests[security]"
```
that executes successfully, the produced Pipfile is unfortunately not valid.

```toml
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true

[packages."requests[security]"]
git = "https://github.com/requests/requests.git"
ref = "master"
```
