### ISSUE TITLE
failed on vcs url in my requirements.txt?

### ISSUE THREAD

**Issue by AlJohri** [kennethreitz/pipenv#516]
hi, @kennethreitz. I tried running `pipenv install` in a repository with an existing requirements.txt. I didn't get any errors but it only ported half of my requirements. This is my requirements file:

```
arrow==0.10.0
blessings==1.6
boto3==1.4.6
coreapi==2.3.1
datadog==0.16.0
dj-database-url==0.4.2
django-codemirror-widget==0.4.1
django-cors-headers==2.1.0
django-debug-toolbar==1.8
django-extensions==1.9.0
django-filter==1.0.4
django-object-actions==0.10.0
Django==1.11.4
djangorestframework-filters==0.10.1
djangorestframework==3.6.4
drf-nested-routers==0.90.0
envdir==0.7
git+https://github.com/pallets/jinja#egg=Jinja2
jinja2-pluralize==0.3.0
newrelic==2.90.0.75
psycopg2==2.7.3.1
pytest==3.2.1
raven==6.1.0
slackclient==1.0.7
slacker==0.9.60
toolz==0.8.2
tweepy==3.5.0
uWSGI==2.0.15
whitenoise==4.0b3
django-tinymce==2.6.0
```

The Pipfile that was output was:
```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true

[packages]
arrow = "==0.10.0"
blessings = "==1.6"
boto3 = "==1.4.6"
coreapi = "==2.3.1"
datadog = "==0.16.0"
dj-database-url = "==0.4.2"
django-codemirror-widget = "==0.4.1"
django-cors-headers = "==2.1.0"
django-debug-toolbar = "==1.8"
django-extensions = "==1.9.0"
django-filter = "==1.0.4"
django-object-actions = "==0.10.0"
django = "==1.11.4"
djangorestframework-filters = "==0.10.1"
djangorestframework = "==3.6.4"
drf-nested-routers = "==0.90.0"
envdir = "==0.7"
```

Seems like it failed on the Jinja2 git url silently?

**Comment by kennethreitz** [comment]
looks like it. want to help fix? :)

**Comment by kennethreitz** [comment]
cannot reproduce with latest.

**Comment by kennethreitz** [comment]
working as expected:

```toml
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true

[packages]
arrow = "==0.10.0"
blessings = "==1.6"
boto3 = "==1.4.6"
coreapi = "==2.3.1"
datadog = "==0.16.0"
dj-database-url = "==0.4.2"
django-codemirror-widget = "==0.4.1"
django-cors-headers = "==2.1.0"
django-debug-toolbar = "==1.8"
django-extensions = "==1.9.0"
django-filter = "==1.0.4"
django-object-actions = "==0.10.0"
Django = "==1.11.4"
djangorestframework-filters = "==0.10.1"
djangorestframework = "==3.6.4"
drf-nested-routers = "==0.90.0"
envdir = "==0.7"
jinja2_pluralize = "==0.3.0"
newrelic = "==2.90.0.75"
psycopg2 = "==2.7.3.1"
pytest = "==3.2.1"
raven = "==6.1.0"
slackclient = "==1.0.7"
slacker = "==0.9.60"
toolz = "==0.8.2"
tweepy = "==3.5.0"
uWSGI = "==2.0.15"
whitenoise = "==4.0b3"
django-tinymce = "==2.6.0"

[packages.Jinja2]
git = "https://github.com/pallets/jinja"
```
