### ISSUE TITLE
`pipenv shell` doesn't work on CircleCI

### ISSUE THREAD

**Issue by tricoder42** [kennethreitz/pipenv#773]
I can't run `pipenv shell` command on CircleCI. It used to work few versions back, but stops working after upgrading to latest version. Relevant information below:

**$ uname -a**
Linux 68d69e284471 4.4.0-92-generic #115~14.04.1-Ubuntu SMP Thu Aug 10 15:06:53 UTC 2017 x86_64 GNU/Linux

**$ python --version**
Python 3.6.2

**$ pipenv --version**
pipenv, version 8.2.2

**$ pipenv --where**
/home/circleci/project

**$ pipenv --venv**
/home/circleci/.local/share/virtualenvs/project-zxI9dQ-Q

**$ pipenv shell**
```
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli.py", line 2057, in shell
    do_shell(three=three, python=python, fancy=fancy, shell_args=shell_args)
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli.py", line 1952, in do_shell
    shell = os.path.abspath(PIPENV_SHELL)
  File "/usr/local/lib/python3.6/posixpath.py", line 369, in abspath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Pipenv 7.0.0** works fine.
**Pipenv 8.0.0** shows this error (even though $SHELL is set to /bin/bash):
```Please ensure that the SHELL environment variable is set before activating shell.``

I appreciate any help! Thank you for great tool :thumbsup:

**Comment by kennethreitz** [comment]
why would you run `shell` on ci?

**Comment by tricoder42** [comment]
Good question, I though that `pipenv shell` is used to activate virtualenv... I did `pipenv shell "cd docs; make html; exit"`. Now I'm using `source $(pipenv --venv)/bin/activate; cd docs; make html` instead.

So, there's nothing wrong with `source $(pipenv --venv)/bin/activate`? `pipenv shell` is for local development only?

**Comment by philfreo** [comment]
@tricoder42 Did you try `pipenv run ...` instead?

**Comment by kennethreitz** [comment]
correct

**Comment by tricoder42** [comment]
@philfreo I tried just now, it works great. Thank you!

**Comment by jamesacampbell** [comment]
Here is an example circleci config.yml I am using for mine:

```
# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  # The python orb contains a set of prepackaged CircleCI configuration you can use repeatedly in your configuration files
  # Orb commands and jobs help you with common scripting around a language/tool
  # so you dont have to copy and paste it everywhere.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@1.2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-and-test: # This is the name of the job, feel free to change it to better match what you're trying to do!
    # These next lines defines a Docker executors: https://circleci.com/docs/2.0/executor-types/
    # You can specify an image from Dockerhub or use one of the convenience images from CircleCI's Developer Hub
    # A list of available CircleCI Docker convenience images are available here: https://circleci.com/developer/images/image/cimg/python
    # The executor is the environment in which the steps below will be executed - below will use a python 3.8 container
    # Change the version below to your required version of python
    docker:
      - image: cimg/python:3.9.7
    # Checkout the code as the first step. This is a dedicated CircleCI step.
    # The python orb's install-packages step will install the dependencies from a Pipfile via Pipenv by default.
    # Here we're making sure we use just use the system-wide pip. By default it uses the project root's requirements.txt.
    # Then run your tests!
    # CircleCI will report the results back to your VCS provider.
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          # app-dir: ~/project/package-directory/  # If you're requirements.txt isn't in the root directory.
          # pip-dependency-file: test-requirements.txt  # if you have a different name for your requirements file, maybe one that combines your runtime and test requirements.
      - run:
          name: Run tests
          # This assumes pytest is installed via the install-package step above
          command: pipenv run pytest

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build-and-test
  
```
