### ISSUE TITLE
Windows: Error launching shell

### ISSUE THREAD

**Issue by floqqi** [kennethreitz/pipenv#811]
I have a project with a simple `Pipfile`:

```toml
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]

bouncer = "*"
flask = "*"
"flask-bouncer" = "*"
"flask-marshmallow" = "*"
"flask-sqlalchemy" = "*"
marshmallow = "*"
"marshmallow-sqlalchemy" = "*"
"psycopg2" = "*"
pyjwt = "*"
sqlalchemy = "*"
webargs = "*"

[requires]
python_version = "3.6"
```

`pipenv install` is working as expected. Creates a new virtual environment and stuff. Now if I want to launch the environment using `pipenv shell`

```shell
C:\Users\fkraus\Projects\test-project>pipenv shell
Launching subshell in virtual environment. Type 'exit' to return.
Clink v0.4.8 [git:d565ad] Copyright (c) 2012-2016 Martin Ridgers
http://mridgers.github.io/clink

Der Befehl "C:\Program" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
```

The error translates to something like `The command "C:\Program" is mistyped or can not be found`.

My Python installation is globally available at `C:\Python36`. Looks like it is searching the Python installation at `C:\Program`. Is this intentionally or do I have a configuration error?

Edit: My virtual environment is properly created at `C:\Users\fkraus\Envs\test-project-_LTCrZAU`.
