### ISSUE TITLE
"Could not find a version that matches coloredlogs" when creating lockfile

### ISSUE THREAD

**Issue by K900** [kennethreitz/pipenv#871]
Pipfile contents:

```toml
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]

flask = "*"
peewee = "*"
"psycopg2" = "*"
coloredlogs = "*"
"openvpn-status-parser" = {git = "https://github.com/ojarva/openvpn-status-parser.git"}
"python-dateutil" = "*"
"dbus-python" = "*"
gunicorn = "*"
telepot = "*"
"pymorphy2" = "*"
"pymorphy2-dicts-ru" = "*"
telethon = "*"
```

Running `pipenv install` results in 

```
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
Could not find a version that matches coloredlogs
Tried: (no version found at all)
```

`pipenv install --skip-lock` works fine and installs all required packages.

Edit: using the latest versions of `pipenv` and all dependencies from PyPI on Python 3.6.2 on Arch Linux.
